create table hibernate_sequence (
    next_val bigint
) ;

insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );

    create table project_entity (
       id int8 generated by default as identity,
        access_code varchar(10),
        admin_id int8,
        name varchar(35),
        primary key (id)
    );

    create table task_entity (
           id int8 generated by default as identity,
            body varchar(10000),
            name varchar(30),
            project_id int8,
            primary key (id)
    );

     create table user_projects (
           user_id int8 not null,
            project_id int8 not null,
            primary key (project_id, user_id)
     );

     create table user_entity (
            id int8 generated by default as identity,
             email varchar(255),
             nickname varchar(25),
             password varchar(255),
             role bytea,
             primary key (id)
     );
